name-template: 'v$next_release_version' # Usando versão no formato vX.X.X
tag-template: 'v$next_release_version'
category-template: '### Features' # Ajuste para suas categorias de mudanças
change-template: '- $title @$author' # Como cada commit será apresentado nas release notes
versioning-strategy: increase # Estratégia para aumentar a versão automaticamente
changelog-generator:
  commit-message-regexp: '^.*$' # Gera release notes de todos os commits

# Template para a criação das notas de lançamento
template: |
  ## $release_title

  $changes
